version: "3.7"
services:
  redis:
    image: redis:5-alpine
    container_name: twitch-plays-crosswords-redis
    volumes:
      - type: volume
        source: redis
        target: "/data"
        volume:
          nocopy: true
    ports:
      - 6379:6379/tcp

  api:
    build:
      context: api
      target: development
      args:
        ENVIRONMENT: dev
    command: >-
      reflex
        --start-service
        --decoration="none"
        --regex='\.go$$'
        --inverse-regex='\.gen.go$$'
      --
        sh -c 'go run .'
    container_name: twitch-plays-crosswords-api
    depends_on:
      - redis
    environment:
      GIN_MODE: release # debug only prints warning messages on startup
      REDIS_HOST: "redis:6379"
    volumes:
      - type: bind
        source: "./api"
        target: "/src"
    expose:
      - 5000
    ports:
      - 5000:5000/tcp
    restart: unless-stopped

  ui:
    build:
      context: ui
      target: development
    command: npm run start
    container_name: twitch-plays-crosswords-ui
    depends_on:
      - api
    environment:
      API_HOST: "api:5000"
    volumes:
      - type: bind
        source: "./ui"
        target: "/src"
    expose:
      - 3000
    ports:
      - 3000:3000/tcp
    restart: unless-stopped

volumes:
  redis: