version: "3.7"
services:
  api:
    container_name: twitch-plays-crosswords-api
    build:
      context: api
      target: development
    command: >-
      reflex
        --start-service
        --decoration="none"
        --regex='\.go$$'
        --inverse-regex='\.gen.go$$'
      --
        sh -c 'go run .'
    depends_on:
      - converter
      - redis
    environment:
      GIN_MODE: release # debug only prints warning messages on startup
      CONVERTER_HOST: "converter:5001"
      REDIS_HOST: "redis:6379"
    volumes:
      - type: bind
        source: "./api"
        target: "/src"
    ports:
      - 5000:5000/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
    restart: unless-stopped

  bot:
    build:
      context: bot
      target: development
    command: >-
      reflex
        --start-service
        --decoration="none"
        --regex='\.go$$'
        --inverse-regex='\.gen.go$$'
      --
        sh -c 'go run .'
    container_name: twitch-plays-crosswords-bot
    depends_on:
      - api
    environment:
      API_HOST: "api:5000"
      ENV: "local"  # local (twitch disabled), development, or production
      TWITCH_USERNAME:
      TWITCH_OAUTH_TOKEN:
    volumes:
      - type: bind
        source: "./bot"
        target: "/src"
    expose:
      - 5002           # this is only needed to test locally
    ports:
      - 5002:5002/tcp  # this is only needed to test locally
    restart: unless-stopped

  converter:
    container_name: twitch-plays-crosswords-converter
    build:
      context: converter
      args:
        REQUIREMENTS_FILENAME: requirements-dev.txt
    working_dir: "/usr/src/app"
    environment:
      PYTHON_UNBUFFERED: "true"
      PYTHONDONTWRITEBYTECODE: "1"
      FLASK_ENV: "development"
    volumes:
      - type: bind
        source: "./converter"
        target: "/usr/src/app"
    ports:
      - 5001:5001/tcp
    restart: unless-stopped

  proxy:
    image: traefik:v2.1
    container_name: twitch-plays-crosswords-proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8080"
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
    expose:
      - 8080
    ports:
      - 8080:8080/tcp
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    container_name: twitch-plays-crosswords-redis
    volumes:
      - type: volume
        source: redis
        target: "/data"
        volume:
          nocopy: true
    ports:
      - 6379:6379/tcp
    restart: unless-stopped

  ui:
    container_name: twitch-plays-crosswords-ui
    build:
      context: ui
      target: development
    command: npm run start
    depends_on:
      - api
    volumes:
      - type: bind
        source: "./ui"
        target: "/src"
    ports:
      - 3000:3000/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
    restart: unless-stopped

volumes:
  redis: