name: Create and publish a Docker image

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_REGISTRY: docker-registry.isomorphism.org

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      # api
      - name: Extract metadata (tags, labels) for Docker
        id: api_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/puzzles-with-chat/api

      - name: Build and push api Docker image
        uses: docker/build-push-action@v4
        with:
          context: api
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}
          labels: ${{ steps.api_meta.outputs.labels }}

      # bot
      - name: Extract metadata (tags, labels) for Docker
        id: bot_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/puzzles-with-chat/bot

      - name: Build and push bot Docker image
        uses: docker/build-push-action@v4
        with:
          context: bot
          push: true
          tags: ${{ steps.bot_meta.outputs.tags }}
          labels: ${{ steps.bot_meta.outputs.labels }}

      # controller
      - name: Extract metadata (tags, labels) for Docker
        id: controller_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/puzzles-with-chat/controller

      - name: Build and push controller Docker image
        uses: docker/build-push-action@v4
        with:
          context: controller
          push: true
          tags: ${{ steps.controller_meta.outputs.tags }}
          labels: ${{ steps.controller_meta.outputs.labels }}

      # ui
      - name: Extract metadata (tags, labels) for Docker
        id: ui_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/puzzles-with-chat/ui

      - name: Build and push ui Docker image
        uses: docker/build-push-action@v4
        with:
          context: ui
          push: true
          tags: ${{ steps.ui_meta.outputs.tags }}
          labels: ${{ steps.ui_meta.outputs.labels }}
